Skip uploading files over 25M
When rclone is not installed (requires version 1.59+)

For now, I'll upload these files manually to R2

diff --git a/website/Makefile b/website/Makefile
--- a/website/Makefile
+++ b/website/Makefile
@@ -56,7 +56,7 @@ all:
 		size=$$(stat -c %s "$(srcdir)/$$file"); \
 		if [[ $${CF_PAGES:+isset} ]] && (( size > 25000000 )) ; then \
 			echo ">>>> R2 >>>>> $(LINKDIR)/$$link_file" ; \
-			rclone copy "$(srcdir)/$$file" "$(bucket):$(LINKDIR)/$$link_file"; \
+			rclone copy "$(srcdir)/$$file" "$(bucket):$(LINKDIR)/$$link_file" || echo "ERROR: $$link_file skipped because rclone unavailable" ; \
 			continue ; \
 		fi ; \
 		echo ">>>> ________  $(LINKDIR)/$$link_file" ; \
